### PR TITLE
refactor: duplicate environ value

### PR DESCRIPTION
**Pull request by akfmdl**
CLEARML_CONFIG_FILE is duplicated

### CODE REVIEW

**Comment by akfmdl** [comment]
@jkhenning hello! could you check this?

**Comment by jkhenning** [comment]
@akfmdl I think the original intent was to add backwards compatibility to the old trains library, so this should not be removed, but rather changed to `TRAINS_CONFIG_FILE`...

**Comment by akfmdl** [comment]
> @akfmdl I think the original intent was to add backwards compatibility to the old trains library, so this should not be removed, but rather changed to `TRAINS_CONFIG_FILE`...

Okay, then i will close the issue.

**Comment by jkhenning** [comment]
If you'd like, you're more than welcome to amend the PR to the original intent 🙂

**Comment by akfmdl** [comment]
@jkhenning I misunderstood what you sad, i fixed again. plz check 😀

**Comment by jkhenning** [comment]
Hi @akfmdl , sorry for the delay, thanks, I'll merge it 🙂

**Pull request merged**
